name: Document Generation

on: 
  push:
    branches:
      - "main"

jobs:
  
  build_docs:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - name: Checkout
      uses: actions/checkout@v3.1.0

    - name: Set up Python
      uses: actions/setup-python@v4.3.0
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install -U sphinx
        python -m pip install sphinx-rtd-theme

    - name: Make the sphinx docs
      run: |
        make -C docs clean
        make -C docs html

    - name: Init new repo in dist folder and commit generated files
      run: |
        cd docs/_build/html/
        git init
        touch .nojekyll
        git add -A
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m 'deploy'
    
    - name: Force push to destination Branch
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages
        force: true
        directory: ./docs/_build/html
