name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thank you for submitting your first issue. Please ensure you have included all the details you know, how to reproduce the issue where applicable, and when possible, how you propose to fix the issue'
        pr-message: 'Thank you for submitting your first Pull Request. Your PR will be reviews, comments made when needed and we will work together to get the PR included where appropriate.'
